version: '3.8'

services:  
  postgresql:
    image: 'bitnami/postgresql:latest'
    container_name: postgres-server
    ports:
     - 5432:5432
    environment:
      - POSTGRESQL_PASSWORD=123
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_DATABASE=shop